In [1]:
import numpy as np
import cv2
np.random.seed(7)

In [2]:
def convolution_layer(inp, F, K, P, S):
    kernel = np.random.rand(F,F,inp.shape[2])
    feature_dim_w = ((inp.shape[0] - F + (2*P))/S)+ 1
    feature_dim_h = ((inp.shape[1] - F + (2*P))/S)+ 1
    feature_map = np.zeros((feature_dim_w,feature_dim_h))
    
    start_i = 0
    end_i = start_i + kernel.shape[0]
    
    for f_i in range(0,feature_dim_w):
        start_j = 0
        end_j = start_j + kernel.shape[0]
        for f_j in range(0, feature_dim_h):
            val = 0
            k_i = 0
            for img_i in range(start_i,end_i):
                k_j = 0
                for img_j in range(start_j, end_j):
                    k_k = 0
                    for img_k in range(0,inp.shape[2]):
                        val +=  inp[img_i][img_j][img_k]*kernel[k_i][k_j][k_k]
                        k_k += 1
                    k_j += 1
                k_i += 1
            feature_map[f_i][f_j] = val
            start_j += 1
            end_j += 1
        start_i += 1
        end_i += 1
    
    print feature_map
            
            
            
    

In [3]:
inp = np.random.randint(1,10,(5,5,2))
for i in range(0,inp.shape[2]):
    print inp[:,:,i]

[[5 4 8 8 9]
 [7 1 1 7 6]
 [9 6 1 9 5]
 [4 9 1 1 7]
 [8 1 8 1 5]]
[[7 4 8 9 8]
 [5 8 8 4 9]
 [8 1 3 7 8]
 [4 4 2 1 8]
 [4 8 8 6 4]]


In [4]:
convolution_layer(inp,3,1,0,1)

[[ 94.  97. 118.]
 [ 82.  74.  88.]
 [ 89.  77.  85.]]


In [ ]:
im = cv2.imread('dog.jpg')